/*
	Trabajo práctico trasversal de la Guía 5 del curso Desarrollo de Apps
	Universidad de La Punta en el marco del proyecto Argentina Programa 4.0

	Integrantes:
		John David Molina Velarde
		Leticia Mores
		Enrique Germán Martínez
		Carlos Eduardo Beltrán
 */

package vistas;


import entidades.Servicio;
import accesoadatos.ServicioData;
import entidades.Servicio.TipoServicio;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import utiles.Utils;

/**
 *
 * @author John David Molina Velarde, Leticia Mores, Enrique Germán Martínez, Carlos Eduardo Beltrán
 */
public class Login extends javax.swing.JFrame {
	
	/**
	 * Constructor
	 */
    public Login() {
        initComponents();
		Utils.sonido1("src/sonidos/Inicio.wav"); // sonido al iniciar
		cargarServicios();
    } //constructor

	/**
	 * carga la bd de Servicios al combo box cbUsuario.
	 * De acá el usuario puede elegir el usurio correspondiente.
	 */
	private void cargarServicios() {
		ServicioData servicioData = new ServicioData(); // conexión con la B.D.
		servicioData.getListaServicios().stream().forEach(servicio -> cbUsuario.addItem(servicio)); //lleno el combo box de usuarios
	}
	
	/**
	 * Para poder poner el ícono de la aplicación en la ventana
	 * @return 
	 */	
	@Override
	public Image getIconImage() { // defino el icono del jFrame
		Image retValue = Toolkit.getDefaultToolkit().
				getImage(ClassLoader.getSystemResource("imagenes/iconoComida.png")); //icono de la aplicación
		return retValue;
	} // getIconImage
	
	
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombre = new javax.swing.JLabel();
        jLPass = new javax.swing.JLabel();
        pwdClave = new javax.swing.JPasswordField();
        jBLogin = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        jLUsuario = new javax.swing.JLabel();
        cbUsuario = new javax.swing.JComboBox<>();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNombre.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setText("Usuario");
        getContentPane().add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLPass.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLPass.setForeground(new java.awt.Color(255, 255, 255));
        jLPass.setText("Password");
        getContentPane().add(jLPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        pwdClave.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        getContentPane().add(pwdClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 150, 20));

        jBLogin.setBackground(new java.awt.Color(71, 78, 194));
        jBLogin.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jBLogin.setForeground(new java.awt.Color(255, 255, 255));
        jBLogin.setText("Login");
        jBLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jBLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 70, -1));

        jBCancel.setBackground(new java.awt.Color(71, 78, 194));
        jBCancel.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jBCancel.setForeground(new java.awt.Color(255, 255, 255));
        jBCancel.setText("Cancel");
        jBCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jBCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 70, -1));

        jLUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        getContentPane().add(jLUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 230, 260));

        getContentPane().add(cbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 150, -1));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoLogin.png"))); // NOI18N
        getContentPane().add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

	
	/**
	 * Este método se llama cuando el usuario hace clíck en el botón Login.
	 * Verifica si la clave es la clave del servicio y en base al tipo de usuario
	 * llama al programa correspondiente:
	 *		- si es administrativo llama a Administración
	 *		- si es mesero llama a Meseros
	 *		- si es recepcion llama a Recepcion
	 *		- si es servicio (cocina, bar, cafeteria) llama a Servicios
	 * @param evt 
	 */
    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
		Servicio servicio = (Servicio) cbUsuario.getSelectedItem();
		if (servicio != null) { // seleccionó un usuario
			//obtengo la clave
			String clave = "";
			for (int i = 0; i < pwdClave.getPassword().length; i++)
				clave += pwdClave.getPassword()[i];
			
			//Verifico si es la clave correcta
			if (servicio.getClave().equals(clave)){
				//abro el programa según el tipo de usuario
				switch (servicio.getTipo()) {
					case ADMINISTRACION:
						Administracion administracion = new Administracion();
						administracion.setVisible(true); //lo hago visible
						administracion.setLocationRelativeTo(null); //lo abro en el centro
						dispose(); // cierro la ventana de login
						break;
					case MESERO:
						Meseros meseros = new Meseros(servicio);
						meseros.setVisible(true); //lo hago visible
						meseros.setLocationRelativeTo(null); //lo abro en el centro
						dispose(); // cierro la ventana de login
						break;
					case RECEPCION:
						Recepcion recepcion = new Recepcion(servicio);
						recepcion.setVisible(true); //lo hago visible
						recepcion.setLocationRelativeTo(null); //lo abro en el centro
						dispose(); // cierro la ventana de login
						break;
					case SERVICIO:
						Despacho despacho = new Despacho(servicio);
						despacho.setVisible(true); //lo hago visible
						despacho.setLocationRelativeTo(null); //lo abro en el centro
						dispose(); // cierro la ventana de login
						break;
					default: 
						JOptionPane.showMessageDialog(null, "Tipo de usuario no válido. Llame al Servicio técnico", "Tipo de usuario inválido", JOptionPane.ERROR_MESSAGE);
						break;
				}
			} else { //clave errada
				JOptionPane.showMessageDialog(null, "Clave no válida", "Clave errada", JOptionPane.ERROR_MESSAGE);
			}
		} else { // no seleccionó ningún usuario
			JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario", "Usuario no seleccionado", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_jBLoginActionPerformed

	
	
	/**
	 * Este método se llama cuando el usuario hace click en el botón cancel.
	 * @param evt 
	 */
    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        dispose(); //Cerrar la ventana
    }//GEN-LAST:event_jBCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Servicio> cbUsuario;
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBLogin;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPass;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JPasswordField pwdClave;
    // End of variables declaration//GEN-END:variables
}
